# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
name: vale-check
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  vale-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.1
        with:
          files: 'src'
          fail_on_error: 'true'
          reporter: 'github-pr-review'
